// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// FSVDupdater
List FSVDupdater(NumericMatrix ratingMat, NumericMatrix U, NumericMatrix V, double gamma, double lambda, List itemIdx, int nrfeat, int feat, double globalbaseline, NumericVector baseline_users, NumericVector baseline_items, double minimum, double maximum);
RcppExport SEXP rrecsys_FSVDupdater(SEXP ratingMatSEXP, SEXP USEXP, SEXP VSEXP, SEXP gammaSEXP, SEXP lambdaSEXP, SEXP itemIdxSEXP, SEXP nrfeatSEXP, SEXP featSEXP, SEXP globalbaselineSEXP, SEXP baseline_usersSEXP, SEXP baseline_itemsSEXP, SEXP minimumSEXP, SEXP maximumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ratingMat(ratingMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type U(USEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< List >::type itemIdx(itemIdxSEXP);
    Rcpp::traits::input_parameter< int >::type nrfeat(nrfeatSEXP);
    Rcpp::traits::input_parameter< int >::type feat(featSEXP);
    Rcpp::traits::input_parameter< double >::type globalbaseline(globalbaselineSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type baseline_users(baseline_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type baseline_items(baseline_itemsSEXP);
    Rcpp::traits::input_parameter< double >::type minimum(minimumSEXP);
    Rcpp::traits::input_parameter< double >::type maximum(maximumSEXP);
    rcpp_result_gen = Rcpp::wrap(FSVDupdater(ratingMat, U, V, gamma, lambda, itemIdx, nrfeat, feat, globalbaseline, baseline_users, baseline_items, minimum, maximum));
    return rcpp_result_gen;
END_RCPP
}
