# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FSVDupdaterBiases <- function(ratingMat, learningRate, regCoef, itemIdx, nrfeat, steps, globalbaseline) {
    .Call('_rrecsys_FSVDupdaterBiases', PACKAGE = 'rrecsys', ratingMat, learningRate, regCoef, itemIdx, nrfeat, steps, globalbaseline)
}

FSVDupdater <- function(ratingMat, learningRate, regCoef, itemIdx, nrfeat, steps) {
    .Call('_rrecsys_FSVDupdater', PACKAGE = 'rrecsys', ratingMat, learningRate, regCoef, itemIdx, nrfeat, steps)
}

FSVDupdaterSparseMatBiases <- function(sparseRatingMat, learningRate, regCoef, nrfeat, steps, nr_users, nr_items, globalbaseline) {
    .Call('_rrecsys_FSVDupdaterSparseMatBiases', PACKAGE = 'rrecsys', sparseRatingMat, learningRate, regCoef, nrfeat, steps, nr_users, nr_items, globalbaseline)
}

FSVDupdaterSparseMat <- function(sparseRatingMat, learningRate, regCoef, nrfeat, steps, nr_users, nr_items) {
    .Call('_rrecsys_FSVDupdaterSparseMat', PACKAGE = 'rrecsys', sparseRatingMat, learningRate, regCoef, nrfeat, steps, nr_users, nr_items)
}

itemMFCount <- function(sim_index, user_vector, pt) {
    .Call('_rrecsys_itemMFCount', PACKAGE = 'rrecsys', sim_index, user_vector, pt)
}

ItemSimil <- function(x, DAMP) {
    .Call('_rrecsys_ItemSimil', PACKAGE = 'rrecsys', x, DAMP)
}

ItemSimilSparseMat <- function(x, dim, DAMP) {
    .Call('_rrecsys_ItemSimilSparseMat', PACKAGE = 'rrecsys', x, dim, DAMP)
}

predictIB <- function(data, s, simIndexKNN, simil, neigh, maximum, minimum, ItMeans, clamp) {
    .Call('_rrecsys_predictIB', PACKAGE = 'rrecsys', data, s, simIndexKNN, simil, neigh, maximum, minimum, ItMeans, clamp)
}

predictUB <- function(data, s, simIndexKNN, simil, neigh, maximum, minimum, UsrMeans, clamp) {
    .Call('_rrecsys_predictUB', PACKAGE = 'rrecsys', data, s, simIndexKNN, simil, neigh, maximum, minimum, UsrMeans, clamp)
}

predictUBSparse <- function(data, dim, s, simIndexKNN, simil, neigh, maximum, minimum, UsrMeans, clamp) {
    .Call('_rrecsys_predictUBSparse', PACKAGE = 'rrecsys', data, dim, s, simIndexKNN, simil, neigh, maximum, minimum, UsrMeans, clamp)
}

predictUVBiases <- function(s, U, V, minimum, maximum, blglo, blusr, blitm, clamp) {
    .Call('_rrecsys_predictUVBiases', PACKAGE = 'rrecsys', s, U, V, minimum, maximum, blglo, blusr, blitm, clamp)
}

predictUV <- function(s, U, V, minimum, maximum, clamp) {
    .Call('_rrecsys_predictUV', PACKAGE = 'rrecsys', s, U, V, minimum, maximum, clamp)
}

UserSimil <- function(x, damp) {
    .Call('_rrecsys_UserSimil', PACKAGE = 'rrecsys', x, damp)
}

UserSimilSparseMat <- function(x, dim, damp) {
    .Call('_rrecsys_UserSimilSparseMat', PACKAGE = 'rrecsys', x, dim, damp)
}

weightedSlopeOneRM <- function(x) {
    .Call('_rrecsys_weightedSlopeOneRM', PACKAGE = 'rrecsys', x)
}

