# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FSVDupdater <- function(ratingMat, U, V, gamma, lambda, itemIdx, nrfeat, feat, globalbaseline, baseline_users, baseline_items, minimum, maximum) {
    .Call('rrecsys_FSVDupdater', PACKAGE = 'rrecsys', ratingMat, U, V, gamma, lambda, itemIdx, nrfeat, feat, globalbaseline, baseline_users, baseline_items, minimum, maximum)
}

